# NAIVE BYES

What is Naive Bayes?

Naive Bayes is a Supervised Machine Learning algorithm mainly used for:

Classification problems,
Text classification,
Spam detection,
Sentiment analysis,
Medical diagnosis,
Recommendation systems

It is based on Bayes Theorem of probability (CONDITIONAL PROBABILITY)

# Types of Naive Bayes

# Gaussian Naive Bayes

Used when data is:

Continuous
Normally distributed

Example:

Height
Weight
Salary

Mostly numerical datasets

work based on 
```math
f(x)=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}

```

# Multinomial Naive Bayes

Used for:

Text data
Word counts
NLP

Example:

Spam detection,
News classification

Works on frequency/counts

# Bernoulli Naive Bayes

Used for:

Binary features
Yes/No type data

Example:

Word present or absent

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("loan_data.csv")
df

,Age,Income,Education,Employment,Credit_Score,Loan_Amount,Marital_Status,Loan_Approved
0,35,High,Graduate,Employed,Good,Low,Married,Yes
1,28,Low,Undergraduate,Unemployed,Poor,High,Single,No
2,45,Medium,Graduate,Employed,Good,Medium,Married,Yes
3,32,High,Postgraduate,Employed,Excellent,Low,Single,Yes
4,50,Low,Undergraduate,Unemployed,Poor,High,Divorced,No
...,...,...,...,...,...,...,...,...
95,50,Medium,Postgraduate,Employed,Good,Low,Married,Yes
96,36,High,Graduate,Self-Employed,Excellent,Low,Single,Yes
97,56,Low,Undergraduate,Unemployed,Poor,High,Divorced,No
98,42,Medium,Graduate,Employed,Good,Medium,Married,Yes
99,53,High,Postgraduate,Employed,Excellent,Low,Married,Yes

In [4]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
col = df.select_dtypes(include=['object']).columns
df[col] = oe.fit_transform(df[col])

C:\Users\piyus\AppData\Local\Temp\ipykernel_11108\2211458973.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col = df.select_dtypes(include=['object']).columns

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             100 non-null    int64
 1   Income          100 non-null    float64
 2   Education       100 non-null    float64
 3   Employment      100 non-null    float64
 4   Credit_Score    100 non-null    float64
 5   Loan_Amount     100 non-null    float64
 6   Marital_Status  100 non-null    float64
 7   Loan_Approved   100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

In [6]:
df.head()

,Age,Income,Education,Employment,Credit_Score,Loan_Amount,Marital_Status,Loan_Approved
0,35,0.0,0.0,0.0,1.0,1.0,1.0,1.0
1,28,1.0,2.0,2.0,2.0,0.0,2.0,0.0
2,45,2.0,0.0,0.0,1.0,2.0,1.0,1.0
3,32,0.0,1.0,0.0,0.0,1.0,2.0,1.0
4,50,1.0,2.0,2.0,2.0,0.0,0.0,0.0

In [7]:
x = df.drop("Loan_Approved", axis=1)
y = df["Loan_Approved"]

In [8]:
from sklearn.model_selection import train_test_split
x_train ,x_test , y_train , y_test = train_test_split(x,y, test_size=0.2 , random_state=42)

In [9]:
model = GaussianNB()

In [10]:
model.fit(x_train, y_train)

GaussianNB()

In [11]:
y_pred = model.predict(x_test)
print("Prediction:", y_pred)

Prediction: [1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]

In [12]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 1.0

In [13]:
from sklearn.naive_bayes import BernoulliNB

In [14]:
model = BernoulliNB(alpha=1.0)

alpha = smoothing value

Used to avoid zero probability problem

In [15]:
model.fit(x_train, y_train)

BernoulliNB()

In [16]:
y_pred = model.predict(x_test)
y_pred

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0.])

In [17]:
model.predict([[53 , 0 ,0 ,0,0,1,2,]])

c:\Users\piyus\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(

array([1.])

In [18]:
from sklearn.naive_bayes import BernoulliNB
y_pred = model.predict(x_test)

In [19]:
model = BernoulliNB(alpha=1.0)

In [20]:
model.fit(x_train, y_train)

BernoulliNB()

In [21]:
y_pred = model.predict(x_test)
y_pred

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0.])

# DIFFERNCE B/W GAUSSIANB , BERNOULLIINB , MULTINOMIALNB

| Feature         | GaussianNB     | BernoulliNB | MultinomialNB   |
| --------------- | -------------- | ----------- | --------------- |
| Data Type       | Continuous     | Binary      | Count/Frequency |
| Example         | Height, Weight | Yes/No      | Word counts     |
| Values          | 12.5, 170      | 0 or 1      | 0,1,2,3         |
| Best For        | Numerical data | Binary text | NLP/Text        |
| Uses Frequency? | No             | No          | Yes             |




```TEXT
Gaussian → Continuous numbers
Bernoulli → Presence/Absence
Multinomial → Frequency/Counts
```

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [23]:
data = {
    'Height': [170, 180, 160, 175, 155, 190],
    'Weight': [65, 85, 50, 75, 48, 90],
    'Class': ['Fit', 'Unfit', 'Fit', 'Unfit', 'Fit', 'Unfit']
}

df = pd.DataFrame(data)
df

   Height  Weight  Class
0     170      65    Fit
1     180      85  Unfit
2     160      50    Fit
3     175      75  Unfit
4     155      48    Fit
5     190      90  Unfit

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Class"] = le.fit_transform(df["Class"])

In [25]:
df.head()

   Height  Weight  Class
0     170      65      0
1     180      85      1
2     160      50      0
3     175      75      1
4     155      48      0

In [26]:
X = df[['Height', 'Weight']]
y = df['Class']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
model = GaussianNB()

In [29]:
model.fit(X_train, y_train)

GaussianNB()

In [30]:
y_pred = model.predict(X_test)
y_pred

array([1, 1])

In [31]:
print("Prediction:", y_pred)
print("Accuracy:", accuracy_score(y_test, y_pred))

Prediction: [1 1]
Accuracy: 0.5

In [32]:
import warnings
warnings.filterwarnings("ignore")
model.predict([[170 , 65]])

array([1])

In [33]:
new_data = [[172, 70]]
prediction = model.predict(new_data)
print(prediction)
accuracy_score(y_test, y_pred)

[1]

0.5

# PERFORMING MULTINOMIAL NB /

In [34]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [36]:
df = pd.read_csv("spam.csv")
df

                                              message label
0   Congratulations! You won a free iPhone. Claim now  spam
1                       Hey, are we meeting tomorrow?   ham
2              Limited time offer! Win cash prize now  spam
3           Please send the project report by evening   ham
4              Free entry in a lucky draw. Click here  spam
5                  Can you call me when you are free?   ham
6                 You have been selected for a reward  spam
7                  Let's have lunch together tomorrow   ham
8                  URGENT! Your account has won money  spam
9              Meeting has been rescheduled to Monday   ham
10                       Exclusive offer just for you  spam
11                   Happy birthday! Have a great day   ham
12                   Win a free vacation ticket today  spam
13                Please review the attached document   ham
14                       Earn money quickly from home  spam
15             Are you available for the class today?   ham
16                    Claim your free cashback reward  spam
17                        Thank you for your purchase   ham
18                 Get free coupons and discounts now  spam
19           Your order has been shipped successfully   ham
20                  Lowest prices guaranteed. Buy now  spam
21               Can we discuss the assignment later?   ham
22                 You are selected as a lucky winner  spam
23                      Family dinner planned tonight   ham
24          Free recharge available for limited users  spam
25               Your interview is scheduled tomorrow   ham
26       Congratulations! You received a bonus reward  spam
27                    Please update the meeting notes   ham
28                 Special discount offer ending soon  spam
29                            Hope you are doing well   ham

In [37]:
le = LabelEncoder()

In [38]:
# df['label'] = df['label'].map({'ham': 0,'spam': 1})  
# df['label'] = df['label'].replace({'ham': 0,'spam': 1})
df['label'] = le.fit_transform(df['label'])
df

                                              message  label
0   Congratulations! You won a free iPhone. Claim now      1
1                       Hey, are we meeting tomorrow?      0
2              Limited time offer! Win cash prize now      1
3           Please send the project report by evening      0
4              Free entry in a lucky draw. Click here      1
5                  Can you call me when you are free?      0
6                 You have been selected for a reward      1
7                  Let's have lunch together tomorrow      0
8                  URGENT! Your account has won money      1
9              Meeting has been rescheduled to Monday      0
10                       Exclusive offer just for you      1
11                   Happy birthday! Have a great day      0
12                   Win a free vacation ticket today      1
13                Please review the attached document      0
14                       Earn money quickly from home      1
15             Are you available for the class today?      0
16                    Claim your free cashback reward      1
17                        Thank you for your purchase      0
18                 Get free coupons and discounts now      1
19           Your order has been shipped successfully      0
20                  Lowest prices guaranteed. Buy now      1
21               Can we discuss the assignment later?      0
22                 You are selected as a lucky winner      1
23                      Family dinner planned tonight      0
24          Free recharge available for limited users      1
25               Your interview is scheduled tomorrow      0
26       Congratulations! You received a bonus reward      1
27                    Please update the meeting notes      0
28                 Special discount offer ending soon      1
29                            Hope you are doing well      0

In [59]:
X = df["message"]
y = df["label"]

In [60]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42)

In [61]:
vectorizer = CountVectorizer()
X_train_v = vectorizer.fit_transform(X_train)
X_test_v = vectorizer.transform(X_test)

In [62]:
model = MultinomialNB()

In [63]:
model.fit(X_train_v, y_train)

MultinomialNB()

In [ ]:
# y_pred = model.predict(X_test_v)
# y_pred

array([0, 1, 1, 1, 1, 0])

In [ ]:
# accuracy_score( y_test,y_pred)

0.5